import type { Metadata } from "next";
import { Inter } from 'next/font/google';
import "./globals.css";
import { Navbar } from "./_components/navbar/Navbar";
import { Toaster } from "react-hot-toast";
import Footer from "./_components/footer/Footer";
import Provider from "@/provider";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} `}
      >
        
          <Provider>
          <Toaster/>
          <Navbar />
          {children}
          <Footer/>
          </Provider>
      </body>
    </html>
  );
}
